import os

NAGAD_BASE_URL = os.environ.get("NAGAD_BASE_URL")
NAGAD_MERCHANT_ID = os.environ.get("NAGAD_MERCHANT_ID")
NAGAD_PUBLIC_KEY = os.environ.get("NAGAD_PUBLIC_KEY")
NAGAD_PRIVATE_KEY = os.environ.get("NAGAD_PRIVATE_KEY")
NAGAD_MERCHANT_CALLBACK_URL = os.environ.get("NAGAD_MERCHANT_CALLBACK_URL")
NAGAD_INTIATE_PAYMENT_URL = os.environ.get("NAGAD_INTIATE_PAYMENT_URL")
NAGAD_COMPLETE_PAYMENT_URL = os.environ.get("NAGAD_COMPLETE_PAYMENT_URL")
